const app=document.getElementById('app'),net=document.getElementById('net');
const SUPABASE_URL='https://xbefmjcagmlqptkrrtse.supabase.co';
const SUPABASE_PUBLISHABLE='sb_publishable_J7wi8MGYRKcVCE7fQRsMxg_bPtEd44e';
const qs=new URLSearchParams(location.search);
function bootTicket(){try{const h=new URLSearchParams(location.hash.replace(/^#/,'')),b=h.get('ticket');if(!b)return null;let z=String(b).replace(/-/g,'+').replace(/_/g,'/');z+='='.repeat((4-(z.length%4))%4);const bin=atob(z);const bytes=Uint8Array.from(bin,c=>c.charCodeAt(0));return JSON.parse(new TextDecoder('utf-8').decode(bytes))}catch{return null}}
const boot=bootTicket();
const pathPart=location.pathname.split('/').filter(Boolean).pop()||'';
const qrToken=decodeURIComponent(qs.get('token')||boot?.token||((pathPart&&pathPart!=='ficha'&&pathPart!=='index.html')?pathPart:'')||'');
let token=qrToken;
const missionId=String(boot?.missionId||qs.get('missionId')||'');
const externalMode=location.hostname.includes('github.io')||location.hostname.endsWith('.supabase.co')||qs.has('token');
let mission=null,gpsWatch=null,lastGps=0,lastRemoteError='',submittingStart=false,submittingReturn=false,submissionProgress='',remoteConnected=false,remoteReadBusy=false,flushBusy=false,lastRemoteOk=0;
const checklistItems=['Extintor','Macaco','Chave de rodas','Estepe','Parte elétrica','Lataria','Óleo lubrificante','Água','Fluido de freio','Pneus','Triângulo','Limpeza','CRLV','Bateria','Pintura','Para-brisas / Vidros'];
const requiredShots=[{key:'FRENTE',label:'Frente da VTR'},{key:'TRASEIRA',label:'Traseira da VTR'},{key:'LATERAL_ESQUERDA',label:'Lateral esquerda'},{key:'LATERAL_DIREITA',label:'Lateral direita'},{key:'PAINEL',label:'Painel / hodômetro'}];
const shotState={SAÍDA:{},RETORNO:{}};
let returnMode=false,initializedState=false;
const sendState={start:{submitted:false,id:'',submittedAt:''},return:{submitted:false,id:'',submittedAt:''}};
const draftKey='sivtr-draft-'+token; let draft={}; try{draft=JSON.parse(localStorage.getItem(draftKey)||'{}')||{}}catch{}
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const fmtDT=v=>{if(!v)return 'horário não registrado';try{return new Date(v).toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit'})}catch{return String(v)}};
function localPhotoRows(stage){return requiredShots.map(x=>{const st=shotState[stage]?.[x.key];return st?{caption:x.label,event_at:st.capturedAt,local:true,syncQueuedAt:st.syncQueuedAt||null}:null}).filter(Boolean)}
function photoRows(stage){const remote=(Array.isArray(mission?.media)?mission.media:[]).filter(x=>String(x.stage||'').toUpperCase().startsWith(stage.toUpperCase()));const byCaption=new Map(remote.map(x=>[String(x.caption||''),x]));for(const x of localPhotoRows(stage))if(!byCaption.has(x.caption))byCaption.set(x.caption,x);return [...byCaption.values()]}
function photoSummary(stage){const rows=photoRows(stage);if(!rows.length)return '';return `<div class="photo-log"><div class="section-label">Fotos registradas — ${stage}</div>${rows.map(x=>`<div class="photo-log-row"><b>${esc(x.caption||'Foto')}</b><span>Capturada em ${esc(fmtDT(x.event_at))}</span>${x.received_at?`<small>Recebida pelo SIVTR em ${esc(fmtDT(x.received_at))}</small>`:(x.local&&x.syncQueuedAt?`<small>Envio registrado no celular em ${esc(fmtDT(x.syncQueuedAt))} • aguardando confirmação do central</small>`:'<small>Aguardando sincronização com o SIVTR central</small>')}</div>`).join('')}</div>`}
function setSubmitProgress(text){submissionProgress=text||'';const el=document.getElementById('submissionProgress');if(el)el.textContent=submissionProgress}

function updateNet(){const online=navigator.onLine;if(!online){net.textContent='OFFLINE';net.classList.add('off');return}if(remoteConnected||Date.now()-lastRemoteOk<5000){net.textContent='ONLINE';net.classList.remove('off')}else{net.textContent='SINCRONIZANDO';net.classList.remove('off')}}
window.addEventListener('online',()=>{updateNet();flushQueue();refresh()});window.addEventListener('offline',()=>{remoteConnected=false;updateNet()});updateNet();
function ticketFromHash(){return boot||bootTicket()}
function idb(){return new Promise((resolve,reject)=>{const r=indexedDB.open('sivtr-mobile',5);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains('missions'))d.createObjectStore('missions',{keyPath:'token'});if(!d.objectStoreNames.contains('queue'))d.createObjectStore('queue',{keyPath:'id'});if(!d.objectStoreNames.contains('drafts'))d.createObjectStore('drafts',{keyPath:'token'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function put(store,val){const d=await idb();return new Promise((res,rej)=>{const t=d.transaction(store,'readwrite');t.objectStore(store).put(val);t.oncomplete=res;t.onerror=()=>rej(t.error)})}
async function get(store,key){const d=await idb();return new Promise((res,rej)=>{const r=d.transaction(store).objectStore(store).get(key);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function all(store){const d=await idb();return new Promise((res,rej)=>{const r=d.transaction(store).objectStore(store).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function del(store,key){const d=await idb();return new Promise((res,rej)=>{const t=d.transaction(store,'readwrite');t.objectStore(store).delete(key);t.oncomplete=res;t.onerror=()=>rej(t.error)})}
async function persistMobileState(){try{await put('drafts',{token,draft,shots:shotState,returnMode,sendState,submissionProgress,at:new Date().toISOString()})}catch{}}
async function restoreMobileState(){try{const x=await get('drafts',token);if(x){draft=x.draft||draft;Object.assign(shotState.SAÍDA,x.shots?.SAÍDA||{});Object.assign(shotState.RETORNO,x.shots?.RETORNO||{});returnMode=!!x.returnMode;Object.assign(sendState.start,x.sendState?.start||{});Object.assign(sendState.return,x.sendState?.return||{});submissionProgress=x.submissionProgress||submissionProgress}}catch{}initializedState=true}
function saveDraftField(id,value){draft[id]=value;try{localStorage.setItem(draftKey,JSON.stringify(draft))}catch{}persistMobileState()}
function bindDraftAutosave(){document.querySelectorAll('input:not([type=file]),textarea,select').forEach(el=>{const key=el.id||el.name;if(!key)return;el.addEventListener(el.type==='radio'||el.type==='checkbox'||el.tagName==='SELECT'?'change':'input',()=>{if(el.type==='radio'){if(el.checked)saveDraftField(key,el.value)}else saveDraftField(key,el.type==='checkbox'?el.checked:el.value)})})}
function restoreDraftToDom(){for(const [k,v] of Object.entries(draft)){const el=document.getElementById(k);if(el&&el.type!=='file'){if(el.type==='checkbox')el.checked=!!v;else el.value=v}document.querySelectorAll(`input[type=radio][name="${CSS.escape(k)}"]`).forEach(r=>r.checked=r.value===v)};for(const stage of ['SAÍDA','RETORNO'])for(const x of requiredShots){const s=shotState[stage][x.key];if(!s)continue;const p=document.getElementById(`preview_${stage}_${x.key}`),st=document.getElementById(`state_${stage}_${x.key}`);if(p)p.innerHTML=`<img src="${s.dataUrl}" alt="${x.key}">`;if(st){st.textContent='Foto pronta • '+fmtDT(s.capturedAt);st.classList.add('done')}}}
async function fetchTimeout(url,opt={},ms=12000){const ctrl=new AbortController(),t=setTimeout(()=>ctrl.abort(),ms);try{return await fetch(url,{...opt,signal:ctrl.signal})}catch(e){if(e?.name==='AbortError')throw new Error('Tempo limite na comunicação com o SIVTR central.');throw e}finally{clearTimeout(t)}}
function markRemoteOk(){remoteConnected=true;lastRemoteOk=Date.now();lastRemoteError='';updateNet()}
function markRemoteFail(msg=''){remoteConnected=false;if(msg&&!/tempo limite|network|fetch|offline|aborted/i.test(String(msg)))lastRemoteError=String(msg);updateNet()}
async function supabaseRpc(name,payload,timeout=12000){const r=await fetchTimeout(`${SUPABASE_URL}/rest/v1/rpc/${name}`,{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json','apikey':SUPABASE_PUBLISHABLE,'Cache-Control':'no-cache'},body:JSON.stringify(payload)},timeout);let d=null;try{d=await r.json()}catch{}if(!r.ok)throw new Error(d?.message||d?.error||`HTTP ${r.status}`);markRemoteOk();return d}
function isTransientRemoteError(e){return /tempo limite|network|fetch|offline|aborted|load failed|internet|connection|conexão|failed to fetch/i.test(String(e?.message||e||''))}
async function remoteMission(){
  let oldErr=null,d=null;
  try{d=await supabaseRpc('sivtr_get_mission',{p_token:token},10000)}catch(e){oldErr=e}
  if(d){d=Array.isArray(d)?d[0]:d;return d}
  if(oldErr&&!/missão não encontrada|mission not found/i.test(String(oldErr?.message||''))){markRemoteFail(oldErr?.message);throw oldErr}
  if(missionId){
    try{d=await supabaseRpc('sivtr_get_mission_v2',{p_token:token,p_mission_id:missionId},10000)}
    catch(e){
      const msg=String(e?.message||'');
      if(/could not find the function|schema cache|p_mission_id|sivtr_get_mission_v2/i.test(msg)){if(oldErr)throw oldErr;return null}
      markRemoteFail(msg);throw (oldErr||e)
    }
  }
  d=Array.isArray(d)?d[0]:d;
  return d||null;
}
async function send(kind,data,allowQueue=true){
  if(!navigator.onLine){if(allowQueue){await queue(kind,data);markRemoteFail('offline');return {ok:true,queuedLocal:true}}throw new Error('Sem internet. Ação aguardando sincronização.')}
  if(externalMode){
    let last=null;
    for(let attempt=0;attempt<3;attempt++){
      try{return await supabaseRpc('sivtr_enqueue_action',{p_token:token,p_action_type:kind,p_payload:data||{}},12000)}
      catch(e1){
        last=e1;
        const msg1=String(e1?.message||'');
        if(/missão não encontrada|mission not found/i.test(msg1)&&missionId){
          try{return await supabaseRpc('sivtr_enqueue_action_v2',{p_token:token,p_mission_id:missionId,p_action_type:kind,p_payload:data||{}},12000)}
          catch(e2){last=e2;const msg2=String(e2?.message||'');if(!/could not find the function|schema cache|p_mission_id|sivtr_enqueue_action_v2/i.test(msg2)&&!isTransientRemoteError(e2))break}
        }else if(!isTransientRemoteError(e1)&&!/404|function|schema cache/i.test(msg1))break;
        if(attempt<2)await new Promise(r=>setTimeout(r,350*(attempt+1)));
      }
    }
    const msg=String(last?.message||'Falha de sincronização');
    if(allowQueue){await queue(kind,data);markRemoteFail(msg);lastRemoteError='Ação preservada neste aparelho; sincronização automática em andamento.';return {ok:true,queuedLocal:true}}
    throw last||new Error(msg);
  }
  const r=await fetchTimeout(`/api/mobile/${encodeURIComponent(token)}/${kind}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data||{})},12000);const d=await r.json();if(!r.ok||d.ok===false)throw new Error(d.error||'Falha');return d
}
async function queue(kind,data){const dedupe=String(data?.clientPhotoId||data?.clientSubmissionId||'').trim();const id=dedupe?`Q:${token}:${kind}:${dedupe}`:(crypto.randomUUID?crypto.randomUUID():Date.now()+'_'+Math.random());const existing=await get('queue',id).catch(()=>null);const item={id,kind,data,at:existing?.at||new Date().toISOString(),token};await put('queue',item);return item}
async function flushQueue(){if(flushBusy||!navigator.onLine)return;flushBusy=true;try{for(const x of (await all('queue')).sort((a,b)=>a.at.localeCompare(b.at))){try{await send(x.kind,x.data,false);await del('queue',x.id);markRemoteOk()}catch(e){markRemoteFail(e?.message);break}}}finally{flushBusy=false}}
const vtrLabel=m=>[m.vehicle_code||m.vehicleCode,m.vehicle_type||m.vehicleType,m.fab_register||m.fabRegister].filter(Boolean).join(' - ');
const statusOf=m=>String(m.status||'').toUpperCase();
function effectiveStatus(){const st=statusOf(mission);if(sendState.start.submitted&&['PRONTA PARA SAÍDA','AGUARDANDO MOTORISTA',''].includes(st))return 'AGUARDANDO AUTORIZAÇÃO DE SAÍDA';if(sendState.return.submitted&&['EM ANDAMENTO','SAÍDA COM ALERTA'].includes(st))return 'RETORNO INFORMADO';return st}
function hero(){return `<div class="card hero"><h1>${esc(mission.mission_number||mission.missionNumber||'MISSÃO')}</h1><span class="status">${esc(effectiveStatus()||'SINCRONIZANDO')}</span><div class="grid" style="margin-top:10px"><div class="cell"><small>VTR / TIPO / REG</small><b>${esc(vtrLabel(mission)||'-')}</b></div><div class="cell"><small>MOTORISTA / SARAM</small><b>${esc(mission.driver_display||mission.driver||'-')}${mission.driver_saram||mission.driverSaram?` / ${esc(mission.driver_saram||mission.driverSaram)}`:''}</b></div><div class="cell"><small>DESTINO</small><b>${esc(mission.destination||'-')}</b></div><div class="cell"><small>APRESENTAÇÃO</small><b>${esc(mission.presentation_place||mission.presentationPlace||mission.scheduled_departure||mission.departure||'-')}</b></div><div class="cell"><small>SOLICITANTE / SEÇÃO</small><b>${esc((mission.requester_name||mission.requester||'-')+' / '+(mission.requester_section||mission.section||'-'))}</b></div><div class="cell"><small>MISSÃO</small><b>${esc(mission.mission||'-')}</b></div></div></div>`}
function fuelPicker(id){return `<div class="fuel-picker" id="${id}Picker">${['RESERVA','1/4','1/2','3/4','CHEIO'].map(v=>`<button type="button" class="fuel-option" data-value="${v}" onclick="chooseFuel('${id}','${v}',this)">${v}</button>`).join('')}</div><input type="hidden" id="${id}" value="${esc(draft[id]||'')}">`}
window.chooseFuel=(id,v,btn)=>{document.getElementById(id).value=v;document.querySelectorAll(`#${id}Picker .fuel-option`).forEach(x=>x.classList.toggle('selected',x===btn));saveDraftField(id,v)};
function checklist(stage){const opts=[['BOM','Bom'],['REG','Regular'],['RUIM','Ruim'],['FALTA','Falta']];return `<div class="mission-checklist">${checklistItems.map((x,i)=>`<div class="check-row"><div class="check-name">${esc(x)}</div><div class="check-options">${opts.map(([v,l],j)=>`<label class="check-choice ${v.toLowerCase()}"><input type="radio" name="ck_${stage}_${i}" value="${v}" ${j===0?'checked':''}><span>${l}</span></label>`).join('')}</div></div>`).join('')}</div>`}
function photos(stage){return `<div class="photo-grid">${requiredShots.map(x=>`<div class="photo-shot"><div class="shot-title">${esc(x.label)}</div><div class="shot-preview" id="preview_${stage}_${x.key}"><svg viewBox='0 0 24 24' aria-hidden='true'><path d='M4 7h4l1.5-2h5L16 7h4v12H4z' fill='none' stroke='currentColor' stroke-width='1.8'/><circle cx='12' cy='13' r='3.2' fill='none' stroke='currentColor' stroke-width='1.8'/></svg></div><label class="shot-btn">Tirar foto<input type="file" accept="image/*" capture="environment" onchange="captureShot('${stage}','${x.key}',this)"></label><div class="shot-state" id="state_${stage}_${x.key}">Pendente</div></div>`).join('')}</div>`}
window.captureShot=async(stage,key,input)=>{const f=input.files?.[0];if(!f)return;const dataUrl=await compressImage(f);shotState[stage][key]={dataUrl,name:f.name,capturedAt:new Date().toISOString(),syncQueuedAt:null};await persistMobileState();const p=document.getElementById(`preview_${stage}_${key}`),s=document.getElementById(`state_${stage}_${key}`);if(p)p.innerHTML=`<img src="${dataUrl}">`;if(s){const dt=shotState[stage][key]?.capturedAt?fmtDT(shotState[stage][key].capturedAt):'';s.textContent='Foto pronta'+(dt?' • '+dt:'');s.classList.add('done')}};
function compressImage(file){return new Promise((resolve,reject)=>{const img=new Image(),r=new FileReader();r.onload=()=>img.src=r.result;r.onerror=reject;img.onload=()=>{const max=1100,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.64))};r.readAsDataURL(file)})}
function collectChecklist(stage){const o={};checklistItems.forEach((x,i)=>o[x]=document.querySelector(`input[name="ck_${stage}_${i}"]:checked`)?.value||'');return o}
async function uploadShots(stage,submissionId){
  const out=[];let done=0;for(const x of requiredShots)if(!shotState[stage][x.key])throw new Error(`Falta a foto: ${x.label}`);
  await Promise.all(requiredShots.map(async x=>{const st=shotState[stage][x.key];if(st.syncQueuedAt){done++;setSubmitProgress(`Fotos já registradas para sincronização: ${done}/5`);return}const clientPhotoId=`${submissionId}:${stage}:${x.key}`;const r=await send('photo',{stage,caption:x.label,dataUrl:st.dataUrl,eventAt:st.capturedAt,clientPhotoId});st.syncQueuedAt=new Date().toISOString();out.push(r);done++;setSubmitProgress(`Fotos registradas para sincronização: ${done}/5`);await persistMobileState()}));
  setSubmitProgress('5/5 fotos preservadas. Cada foto será aceita uma única vez pelo SIVTR central.');await persistMobileState();return out;
}
function startForm(){return `<div class="card"><h2>Ficha de saída</h2><div class="form-block"><div class="field-km"><label>KM de saída</label><div class="input-unit"><input id="kmStart" type="number" inputmode="numeric" min="1"><span>KM</span></div></div><div class="fuel-block"><div class="section-label">Combustível na saída</div>${fuelPicker('fuelStart')}</div></div><h2 style="margin-top:16px">Checklist de saída</h2>${checklist('SAIDA')}<h2 style="margin-top:16px">Fotos obrigatórias</h2>${photos('SAÍDA')}<label>Observações</label><textarea id="startNotes"></textarea><button id="submitStartBtn" class="btn green" onclick="submitStart()">ENVIAR FICHA / SOLICITAR SAÍDA</button><div id="submitStartStatus" class="submit-status"></div></div>`}
function waitCard(){return `<div class="card departure-wait"><div class="wait-icon">···</div><h2>AGUARDANDO AUTORIZAÇÃO DE SAÍDA</h2><div class="notice warn strong-notice">A VIATURA AINDA NÃO ESTÁ AUTORIZADA A SAIR DA ORGANIZAÇÃO.</div><div class="wait-steps"><span class="done">Ficha preenchida</span><span class="done">Solicitação registrada</span><span class="pending">Aguardando autorização</span></div><div id="submissionProgress" class="small sync-progress">${esc(submissionProgress||'Sincronizando dados com o CDM...')}</div>${photoSummary('SAÍDA')}<div class="small">Esta tela atualiza automaticamente quando o Despachante/Auxiliar autorizar a saída.</div></div>`}
function activeCard(){return `<div class="card departure-ok mission-active"><div class="ok-icon">✓</div><h2>SAÍDA AUTORIZADA — MISSÃO EM ANDAMENTO</h2><div class="notice ok strong-notice">VIATURA AUTORIZADA A SAIR DA ORGANIZAÇÃO.</div>${mission.departure_confirmed_by?`<div class="small center" style="margin-top:8px">Autorizada por ${esc(mission.departure_confirmed_by)} em ${esc(fmtDT(mission.departure_confirmed_at||mission.actual_start))}</div>`:''}${photoSummary('SAÍDA')}<button class="btn orange" onclick="toggleReturn()">TERMINAR MISSÃO / INFORMAR RETORNO</button></div>${returnMode?returnForm():''}`}
function returnForm(){return `<div class="card"><h2>Informar retorno</h2><div class="form-block"><div class="field-km"><label>KM de chegada</label><div class="input-unit"><input id="kmEnd" type="number" inputmode="numeric" min="1"><span>KM</span></div></div><div class="fuel-block"><div class="section-label">Combustível na chegada</div>${fuelPicker('fuelEnd')}</div></div><h2 style="margin-top:16px">Checklist de retorno</h2>${checklist('RETORNO')}<h2 style="margin-top:16px">Fotos obrigatórias do retorno</h2>${photos('RETORNO')}<label>Observações / avarias percebidas</label><textarea id="returnNotes"></textarea><button id="submitReturnBtn" class="btn green" onclick="submitReturn()">ENVIAR RETORNO AO CDM</button><div id="submitReturnStatus" class="submit-status"></div></div>`}
function returnedCard(){return `<div class="card departure-wait"><div class="wait-icon">···</div><h2>RETORNO INFORMADO</h2><div class="notice ok">O retorno foi enviado ao CDM. Aguarde a confirmação de entrada.</div><div id="submissionProgress" class="small sync-progress">${esc(submissionProgress||'Sincronizando retorno e fotos...')}</div>${photoSummary('RETORNO')}</div>`}
function finishedCard(){return `<div class="card departure-ok"><div class="ok-icon">✓</div><h2>MISSÃO ENCERRADA</h2><div class="notice ok">Missão finalizada e registrada no SIVTR.</div></div>`}
function occurrenceCard(){return `<div class="card"><h2>Ocorrência / manutenção</h2><label>Tipo</label><select id="occType"><option>OCORRÊNCIA</option><option>AVARIA</option><option>ACIDENTE</option><option>EMERGÊNCIA</option></select><label>Descrição</label><textarea id="occDesc" placeholder="Descreva o problema observado"></textarea><button class="btn orange" onclick="submitOccurrence()">ENVIAR OCORRÊNCIA</button><button class="btn emergency" onclick="emergency()">ACIONAR DESPACHANTE — EMERGÊNCIA</button></div>`}
function render(){if(!mission)return;const st=effectiveStatus();let body='';if(['PRONTA PARA SAÍDA','AGUARDANDO MOTORISTA',''].includes(st))body=startForm();else if(st==='AGUARDANDO AUTORIZAÇÃO DE SAÍDA')body=waitCard();else if(['EM ANDAMENTO','SAÍDA COM ALERTA'].includes(st))body=activeCard();else if(st==='RETORNO INFORMADO')body=returnedCard();else if(['ENCERRADA','CANCELADA'].includes(st))body=finishedCard();else body=`<div class="card"><div class="notice warn">Estado atual: ${esc(st||'SINCRONIZANDO')}</div></div>`;app.innerHTML=`<div class="wrap">${hero()}${lastRemoteError?`<div class="notice warn">Dados da missão exibidos pelo QR. Sincronização online: ${esc(lastRemoteError)}</div>`:''}${body}${!['ENCERRADA','CANCELADA'].includes(st)?occurrenceCard():''}</div>`;bindDraftAutosave();restoreDraftToDom();for(const id of ['fuelStart','fuelEnd']){const v=document.getElementById(id)?.value;if(v)document.querySelectorAll(`#${id}Picker .fuel-option`).forEach(x=>x.classList.toggle('selected',x.dataset.value===v))}}
window.toggleReturn=()=>{returnMode=!returnMode;persistMobileState();render()};
window.submitStart=async()=>{if(submittingStart||sendState.start.submitted)return;let btn=null;try{const kmEl=document.getElementById('kmStart'),fuelEl=document.getElementById('fuelStart'),notesEl=document.getElementById('startNotes');if(!kmEl||!fuelEl)throw new Error('A ficha de saída foi atualizada enquanto você preenchia. Tente enviar novamente.');const km=Number(kmEl.value),fuel=fuelEl.value,notes=notesEl?.value||'',checklistData=collectChecklist('SAIDA'),reportedAt=new Date().toISOString();if(!km)throw new Error('Informe o KM de saída.');if(!fuel)throw new Error('Informe o combustível de saída.');for(const x of requiredShots)if(!shotState.SAÍDA[x.key])throw new Error(`Falta a foto: ${x.label}`);submittingStart=true;btn=document.getElementById('submitStartBtn');if(btn){btn.disabled=true;btn.textContent='ENVIANDO...'}const status=document.getElementById('submitStartStatus');if(status)status.textContent='Registrando solicitação no CDM...';const submissionId=sendState.start.id||draft.startSubmissionId||((crypto.randomUUID&&crypto.randomUUID())||Date.now()+'_'+Math.random());sendState.start={submitted:true,id:submissionId,submittedAt:reportedAt};draft.startSubmissionId=submissionId;submissionProgress='Solicitação registrada neste aparelho. Enviando ao CDM...';mission.status='AGUARDANDO AUTORIZAÇÃO DE SAÍDA';mission.driver_start_reported_at=reportedAt;await persistMobileState();render();const photoManifest=requiredShots.map(x=>({key:x.key,caption:x.label,capturedAt:shotState.SAÍDA[x.key].capturedAt}));const data={kmStart:km,fuelStart:fuel,checklist:checklistData,notes,actualStart:reportedAt,clientSubmissionId:submissionId,photoManifest};const sr=await send('start',data);submissionProgress=sr?.queuedLocal?'Solicitação preservada neste aparelho. Aguardando conexão para chegar ao CDM.':'Solicitação recebida. Sincronizando as 5 fotos...';await persistMobileState();setSubmitProgress(submissionProgress);await uploadShots('SAÍDA',submissionId);submissionProgress='Ficha e 5 fotos registradas uma única vez. Aguardando autorização do CDM.';await persistMobileState();setSubmitProgress(submissionProgress);setTimeout(refresh,250)}catch(e){submissionProgress='Envio preservado no aparelho. O SIVTR continuará tentando automaticamente. '+String(e?.message||e);await persistMobileState();render()}finally{submittingStart=false;if(btn){btn.disabled=true;btn.textContent='FICHA JÁ ENVIADA'}}};
window.submitReturn=async()=>{if(submittingReturn||sendState.return.submitted)return;let btn=null;try{const kmEl=document.getElementById('kmEnd'),fuelEl=document.getElementById('fuelEnd'),notesEl=document.getElementById('returnNotes');if(!kmEl||!fuelEl)throw new Error('A ficha de retorno foi atualizada enquanto você preenchia. Tente enviar novamente.');const km=Number(kmEl.value),fuel=fuelEl.value,notes=notesEl?.value||'',checklistData=collectChecklist('RETORNO'),reportedAt=new Date().toISOString();if(!km)throw new Error('Informe o KM de chegada.');if(!fuel)throw new Error('Informe o combustível de chegada.');for(const x of requiredShots)if(!shotState.RETORNO[x.key])throw new Error(`Falta a foto: ${x.label}`);submittingReturn=true;btn=document.getElementById('submitReturnBtn');if(btn){btn.disabled=true;btn.textContent='ENVIANDO...'}const submissionId=sendState.return.id||draft.returnSubmissionId||((crypto.randomUUID&&crypto.randomUUID())||Date.now()+'_'+Math.random());sendState.return={submitted:true,id:submissionId,submittedAt:reportedAt};draft.returnSubmissionId=submissionId;mission.status='RETORNO INFORMADO';mission.return_reported_at=reportedAt;submissionProgress='Retorno registrado neste aparelho. Enviando ao CDM...';await persistMobileState();render();const photoManifest=requiredShots.map(x=>({key:x.key,caption:x.label,capturedAt:shotState.RETORNO[x.key].capturedAt}));const data={kmEnd:km,fuelEnd:fuel,checklist:checklistData,notes,reportedAt,clientSubmissionId:submissionId,photoManifest};const rr=await send('return',data);submissionProgress=rr?.queuedLocal?'Retorno preservado neste aparelho. Aguardando conexão com o CDM.':'Retorno recebido. Sincronizando as 5 fotos...';await persistMobileState();setSubmitProgress(submissionProgress);await uploadShots('RETORNO',submissionId);submissionProgress='Retorno e 5 fotos registrados uma única vez. Aguardando confirmação de entrada.';await persistMobileState();setSubmitProgress(submissionProgress);setTimeout(refresh,250)}catch(e){submissionProgress='Retorno preservado no aparelho. O SIVTR continuará tentando automaticamente. '+String(e?.message||e);await persistMobileState();render()}finally{submittingReturn=false;if(btn){btn.disabled=true;btn.textContent='RETORNO JÁ ENVIADO'}}};
window.submitOccurrence=async()=>{try{const desc=document.getElementById('occDesc').value.trim();if(!desc)throw new Error('Descreva a ocorrência.');await send('occurrence',{occurrenceType:document.getElementById('occType').value,description:desc,eventAt:new Date().toISOString()});document.getElementById('occDesc').value='';alert('Ocorrência enviada ao CDM e à manutenção.')}catch(e){alert(e.message)}};
window.emergency=async()=>{if(!confirm('Acionar o Despachante como EMERGÊNCIA?'))return;try{let pos={};try{pos=await new Promise((res,rej)=>navigator.geolocation.getCurrentPosition(p=>res({latitude:p.coords.latitude,longitude:p.coords.longitude}),rej,{enableHighAccuracy:true,timeout:5000}))}catch{}await send('emergency',{...pos,eventAt:new Date().toISOString(),description:'Motorista acionou emergência pela ficha.'});alert('EMERGÊNCIA registrada e enviada ao CDM.')}catch(e){alert(e.message)}};
function clearDraftFieldsOnly(){draft={};try{localStorage.removeItem(draftKey)}catch{}persistMobileState()}
function clearDraft(){draft={};shotState.SAÍDA={};shotState.RETORNO={};try{localStorage.removeItem(draftKey)}catch{}persistMobileState()}
async function refresh(){if(!token||token.length<16){app.innerHTML='<div class="card"><h2>Ficha da missão</h2><div class="notice warn">Link da missão inválido ou sem token.</div></div>';return}if(!initializedState)await restoreMobileState();const cached=await get('missions',token).catch(()=>null),ticket=ticketFromHash();if(!mission){mission=cached?.data||ticket||null;if(mission)render()}if(remoteReadBusy)return;remoteReadBusy=true;try{const data=externalMode?await remoteMission():(await (async()=>{const r=await fetchTimeout('/api/mobile/mission/'+encodeURIComponent(token)+'?_='+Date.now(),{cache:'no-store'},8000),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||`HTTP ${r.status}`);return d.data})());if(data){markRemoteOk();mission=data;await put('missions',{token,data,at:new Date().toISOString()});render()}}catch(e){const raw=String(e?.message||'Falha de sincronização');markRemoteFail(raw);lastRemoteError=/missão não encontrada|mission not found|schema cache|could not find the function/i.test(raw)?'Sincronização da missão pendente. Os dados do QR continuam disponíveis e o sistema tentará novamente automaticamente.':(isTransientRemoteError(e)?'Reconectando ao SIVTR central automaticamente.':raw);if(mission)render();else app.innerHTML=`<div class="card"><h2>Ficha da missão</h2><div class="notice warn">Não foi possível carregar a missão.</div><div class="small">${esc(lastRemoteError)}</div><button class="btn" onclick="refresh()">Tentar novamente</button></div>`}finally{remoteReadBusy=false}}
async function backgroundRefresh(){if(!token||remoteReadBusy)return;remoteReadBusy=true;try{const data=externalMode?await remoteMission():null;if(data){markRemoteOk();const changed=!mission||mission.updated_at!==data.updated_at||mission.status!==data.status||mission.driver_display!==data.driver_display||mission.driver_id!==data.driver_id||mission.fuel_start!==data.fuel_start||mission.km_start!==data.km_start||JSON.stringify(mission.media||[])!==JSON.stringify(data.media||[]);mission=data;await put('missions',{token,data,at:new Date().toISOString()});if(changed)render()}}catch(e){markRemoteFail(e?.message);if(!mission)render()}finally{remoteReadBusy=false}}
if(!externalMode&&'serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js?v=690').catch(()=>{});
refresh().then(flushQueue);setInterval(()=>{flushQueue();backgroundRefresh()},1000);
